version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-agreement-calculator:
    build:
      target: development
    image: ffc-sfi-agreement-calculator-development
    container_name: ffc-sfi-agreement-calculator-development
    ports:
      - "3003:3003"
      - "9232:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
  
  ffc-sfi-agreement-calculator-postgres:
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis_data:/data
    ports:
      - "6381:6379"

volumes:
  redis_data:
  postgres_data: {}
