version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-sfi-agreement-calculator:
    build:
      target: development
    image: ffc-sfi-agreement-calculator-development
    container_name: ffc-sfi-agreement-calculator-test
    command: npm run test
    environment: 
      NODE_ENV: test
      CH_API_GATEWAY: ${CH_API_GATEWAY:-http://api-gateway}
      PACT_BROKER_URL: ${PACT_BROKER_URL:-notset}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME:-notset}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD:-notset}
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-sfi-agreement-calculator-azurite:10000/devstoreaccount1;
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - kafka

  ffc-sfi-agreement-calculator-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
