apiVersion: v2
description: FFC SFI agreement calculator
name: ffc-sfi-agreement-calculator
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
