environment: development
name: ffc-sfi-agreement-calculator
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-agreement-calculator

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-agreement-calculator-config-map

containerSecret:
  name: ffc-sfi-agreement-calculator-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 2
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3003
  messageQueueHost: namespace.servicebus.windows.net
  eligibilitySubscriptionAddress: ffc-sfi-eligibility-check-calculator
  standardsSubscriptionAddress: ffc-sfi-standards-request-calculator
  validateSubscriptionAddress: ffc-sfi-agreement-validate-calculator
  submitSubscriptionAddress: ffc-sfi-agreement-submit-calculator
  calculateSubscriptionAddress: ffc-sfi-agreement-calculate-calculator
  withdrawSubscriptionAddress: ffc-sfi-agreement-withdraw-calculator
  eligibilityTopicAddress: ffc-sfi-eligibility-check
  standardsTopicAddress: ffc-sfi-standards-request
  validateTopicAddress: ffc-sfi-agreement-validate
  submitTopicAddress: ffc-sfi-agreement-submit
  calculateTopicAddress: ffc-sfi-agreement-calculate
  withdrawTopicAddress: ffc-sfi-agreement-withdraw
  paymentTopicAddress: ffc-sfi-payment-request
  requestSbiTopicAddress: ffc-sfi-request-sbi
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-sfi-ffc-sfi-agreement-calculator

postgresService:
  postgresDb: ffc_sfi_agreement_calculator
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-agreement-calculator-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
