{{- include "ffc-helm-library.container-secret" (list . "ffc-sfi-agreement-calculator.container-secret") -}}
{{- define "ffc-sfi-agreement-calculator.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
