{{- include "ffc-helm-library.deployment" (list . "ffc-sfi-agreement-calculator.deployment") -}}
{{- define "ffc-sfi-agreement-calculator.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-sfi-agreement-calculator.container") }}
{{- end -}}
